### PR TITLE
fix search track err

### PR DESCRIPTION
**Pull request by zijipia**
fix search track err

### CODE REVIEW

**Comment by zijipia** [comment]
I use Visual Studio Code so... it auto formats the code

**Comment by zijipia** [comment]
it looks like it works 🤣
image

**Comment by zijipia** [comment]
ahhh... at getRelatedTracks also encountered the same error
image

**Comment by retrouser955** [comment]
TYSM!

**Comment by retrouser955** [comment]
Published! `1.0.2`

**Pull request merged**
